// Code generated by hertz generator.

package main

import (
	"context"
	"net/http"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "hz_test/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	r.GET("basicAuth", func(ctx context.Context, c *app.RequestContext) {
		c.String(http.StatusOK, "hello auth")
	})
	r.POST("v:path/bind", handler.Hello)
}
